version: '3.8'

services:

  app:
    image: node:alpine
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/node/app

  postgres:
    image: postgres:latest
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_DB: Universidade
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5445:5432"
