version: '3.9'

services:

  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/Universidade?schema=public
    volumes:
      - .:/node/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: meu-postgres
    tty: true
    restart: always
    environment:
      POSTGRES_DB: Universidade
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
