version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_DB: Universidade
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5445:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./resources:/docker-entrypoint-initdb.d
